var classes = [
    {
        "name": "ndesaleux\\valueObject\\French\\SecuriteSociale\\InvalidNumber",
        "interface": false,
        "methods": [
            {
                "name": "fromNotMatchingPattern",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "fromWrongNIR",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Exception",
            "self",
            "self"
        ],
        "lcom": 2,
        "length": 10,
        "vocabulary": 6,
        "volume": 25.85,
        "difficulty": 0.8,
        "effort": 20.68,
        "level": 1.25,
        "bugs": 0.01,
        "time": 1,
        "intelligentContent": 32.31,
        "number_operators": 2,
        "number_operands": 8,
        "number_operators_unique": 1,
        "number_operands_unique": 5,
        "cloc": 11,
        "loc": 25,
        "lloc": 14,
        "mi": 107.78,
        "mIwoC": 64.97,
        "commentWeight": 42.8,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 3.5,
        "relativeSystemComplexity": 3.5,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 7,
        "totalSystemComplexity": 7,
        "pageRank": 0.07,
        "afferentCoupling": 2,
        "efferentCoupling": 3,
        "instability": 0.6,
        "violations": {}
    },
    {
        "name": "ndesaleux\\valueObject\\French\\SecuriteSociale\\Number",
        "interface": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getValue",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "isMale",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "isFemale",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getYear",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getMonth",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getDepartement",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getCityNumber",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getOrder",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getNIR",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 10,
        "nbMethods": 9,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 9,
        "nbMethodsGetter": 1,
        "nbMethodsSetters": 0,
        "ccn": 5,
        "ccnMethodMax": 3,
        "externals": [
            "ndesaleux\\valueObject\\French\\SecuriteSociale\\InvalidNumber",
            "ndesaleux\\valueObject\\French\\SecuriteSociale\\InvalidNumber"
        ],
        "lcom": 1,
        "length": 86,
        "vocabulary": 31,
        "volume": 426.06,
        "difficulty": 8.46,
        "effort": 3603.76,
        "level": 0.12,
        "bugs": 0.14,
        "time": 200,
        "intelligentContent": 50.37,
        "number_operators": 28,
        "number_operands": 58,
        "number_operators_unique": 7,
        "number_operands_unique": 24,
        "cloc": 0,
        "loc": 61,
        "lloc": 61,
        "mi": 41.97,
        "mIwoC": 41.97,
        "commentWeight": 0,
        "kanDefect": 0.43,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 3.7,
        "relativeSystemComplexity": 7.7,
        "totalStructuralComplexity": 40,
        "totalDataComplexity": 37,
        "totalSystemComplexity": 77,
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "ndesaleux\\valueObject\\IP\\IPv4",
        "interface": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getValue",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "isPrivate",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "isBroadcast",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 4,
        "nbMethods": 3,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 1,
        "nbMethodsSetters": 0,
        "ccn": 4,
        "ccnMethodMax": 3,
        "externals": [
            "ndesaleux\\valueObject\\IP\\InvalidIP"
        ],
        "lcom": 1,
        "length": 42,
        "vocabulary": 19,
        "volume": 178.41,
        "difficulty": 8.75,
        "effort": 1561.11,
        "level": 0.11,
        "bugs": 0.06,
        "time": 87,
        "intelligentContent": 20.39,
        "number_operators": 12,
        "number_operands": 30,
        "number_operators_unique": 7,
        "number_operands_unique": 12,
        "cloc": 0,
        "loc": 32,
        "lloc": 32,
        "mi": 50.86,
        "mIwoC": 50.86,
        "commentWeight": 0,
        "kanDefect": 0.52,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 2.13,
        "relativeSystemComplexity": 3.13,
        "totalStructuralComplexity": 4,
        "totalDataComplexity": 8.5,
        "totalSystemComplexity": 12.5,
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "ndesaleux\\valueObject\\IP\\InvalidIP",
        "interface": false,
        "methods": [
            {
                "name": "fromInvalidValue",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Exception",
            "Throwable",
            "self"
        ],
        "lcom": 1,
        "length": 10,
        "vocabulary": 7,
        "volume": 28.07,
        "difficulty": 0.75,
        "effort": 21.06,
        "level": 1.33,
        "bugs": 0.01,
        "time": 1,
        "intelligentContent": 37.43,
        "number_operators": 1,
        "number_operands": 9,
        "number_operators_unique": 1,
        "number_operands_unique": 6,
        "cloc": 7,
        "loc": 16,
        "lloc": 9,
        "mi": 111.64,
        "mIwoC": 68.91,
        "commentWeight": 42.73,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 4,
        "relativeSystemComplexity": 4,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 4,
        "totalSystemComplexity": 4,
        "pageRank": 0.07,
        "afferentCoupling": 1,
        "efferentCoupling": 3,
        "instability": 0.75,
        "violations": {}
    },
    {
        "name": "ndesaleux\\valueObject\\Geographical\\ZipCode\\French",
        "interface": false,
        "methods": [
            {
                "name": "validate",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getValue",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 3,
        "ccnMethodMax": 3,
        "externals": [
            "ndesaleux\\valueObject\\Geographical\\ZipCode\\ZipCode",
            "ndesaleux\\valueObject\\Geographical\\ZipCode\\InvalidZipCode",
            "ndesaleux\\valueObject\\Geographical\\ZipCode\\InvalidZipCode"
        ],
        "lcom": 2,
        "length": 24,
        "vocabulary": 13,
        "volume": 88.81,
        "difficulty": 6.43,
        "effort": 570.92,
        "level": 0.16,
        "bugs": 0.03,
        "time": 32,
        "intelligentContent": 13.81,
        "number_operators": 9,
        "number_operands": 15,
        "number_operators_unique": 6,
        "number_operands_unique": 7,
        "cloc": 0,
        "loc": 18,
        "lloc": 18,
        "mi": 58.57,
        "mIwoC": 58.57,
        "commentWeight": 0,
        "kanDefect": 0.29,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 1.25,
        "relativeSystemComplexity": 2.25,
        "totalStructuralComplexity": 2,
        "totalDataComplexity": 2.5,
        "totalSystemComplexity": 4.5,
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 3,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "ndesaleux\\valueObject\\Geographical\\ZipCode\\InvalidZipCode",
        "interface": false,
        "methods": [
            {
                "name": "fromWrongType",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "fromInvalidFormat",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Exception",
            "Throwable",
            "self",
            "Throwable",
            "self"
        ],
        "lcom": 2,
        "length": 22,
        "vocabulary": 9,
        "volume": 69.74,
        "difficulty": 1.25,
        "effort": 87.17,
        "level": 0.8,
        "bugs": 0.02,
        "time": 5,
        "intelligentContent": 55.79,
        "number_operators": 2,
        "number_operands": 20,
        "number_operators_unique": 1,
        "number_operands_unique": 8,
        "cloc": 0,
        "loc": 14,
        "lloc": 14,
        "mi": 61.96,
        "mIwoC": 61.96,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 6,
        "relativeSystemComplexity": 6,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 12,
        "totalSystemComplexity": 12,
        "pageRank": 0.05,
        "afferentCoupling": 2,
        "efferentCoupling": 5,
        "instability": 0.71,
        "violations": {}
    },
    {
        "name": "ndesaleux\\valueObject\\Geographical\\ZipCode\\ZipCode",
        "interface": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "validate",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getValue",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 1,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [],
        "lcom": 1,
        "length": 9,
        "vocabulary": 4,
        "volume": 18,
        "difficulty": 3.5,
        "effort": 63,
        "level": 0.29,
        "bugs": 0.01,
        "time": 4,
        "intelligentContent": 5.14,
        "number_operators": 2,
        "number_operands": 7,
        "number_operators_unique": 2,
        "number_operands_unique": 2,
        "cloc": 0,
        "loc": 15,
        "lloc": 15,
        "mi": 65.42,
        "mIwoC": 65.42,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 0.83,
        "relativeSystemComplexity": 1.83,
        "totalStructuralComplexity": 3,
        "totalDataComplexity": 2.5,
        "totalSystemComplexity": 5.5,
        "pageRank": 0.04,
        "afferentCoupling": 1,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "ndesaleux\\valueObject\\Geographical\\Coordinate\\Latitude",
        "interface": false,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "ccnMethodMax": 0,
        "externals": [
            "ndesaleux\\valueObject\\Geographical\\Coordinate\\Coordinate"
        ],
        "lcom": 0,
        "length": 1,
        "vocabulary": 1,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 2,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 1,
        "number_operators_unique": 0,
        "number_operands_unique": 1,
        "cloc": 0,
        "loc": 5,
        "lloc": 5,
        "mi": 171,
        "mIwoC": 171,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "ndesaleux\\valueObject\\Geographical\\Coordinate\\InvalidCoordinate",
        "interface": false,
        "methods": [
            {
                "name": "fromNotNumerical",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "fromOutOfRange",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Exception",
            "Throwable",
            "self",
            "Throwable",
            "self"
        ],
        "lcom": 2,
        "length": 18,
        "vocabulary": 7,
        "volume": 50.53,
        "difficulty": 1.33,
        "effort": 67.38,
        "level": 0.75,
        "bugs": 0.02,
        "time": 4,
        "intelligentContent": 37.9,
        "number_operators": 2,
        "number_operands": 16,
        "number_operators_unique": 1,
        "number_operands_unique": 6,
        "cloc": 0,
        "loc": 14,
        "lloc": 14,
        "mi": 62.94,
        "mIwoC": 62.94,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 5,
        "relativeSystemComplexity": 5,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 10,
        "totalSystemComplexity": 10,
        "pageRank": 0.26,
        "afferentCoupling": 2,
        "efferentCoupling": 5,
        "instability": 0.71,
        "violations": {}
    },
    {
        "name": "ndesaleux\\valueObject\\Geographical\\Coordinate\\Coordinate",
        "interface": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getValue",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 1,
        "nbMethodsSetters": 0,
        "ccn": 3,
        "ccnMethodMax": 3,
        "externals": [
            "ndesaleux\\valueObject\\Geographical\\Coordinate\\InvalidCoordinate",
            "ndesaleux\\valueObject\\Geographical\\Coordinate\\InvalidCoordinate"
        ],
        "lcom": 1,
        "length": 16,
        "vocabulary": 8,
        "volume": 48,
        "difficulty": 13.5,
        "effort": 648,
        "level": 0.07,
        "bugs": 0.02,
        "time": 36,
        "intelligentContent": 3.56,
        "number_operators": 7,
        "number_operands": 9,
        "number_operators_unique": 6,
        "number_operands_unique": 2,
        "cloc": 0,
        "loc": 19,
        "lloc": 19,
        "mi": 59.93,
        "mIwoC": 59.93,
        "commentWeight": 0,
        "kanDefect": 0.29,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 0.75,
        "relativeSystemComplexity": 1.75,
        "totalStructuralComplexity": 2,
        "totalDataComplexity": 1.5,
        "totalSystemComplexity": 3.5,
        "pageRank": 0.11,
        "afferentCoupling": 2,
        "efferentCoupling": 2,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "ndesaleux\\valueObject\\Geographical\\Coordinate\\Longitude",
        "interface": false,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "ccnMethodMax": 0,
        "externals": [
            "ndesaleux\\valueObject\\Geographical\\Coordinate\\Coordinate"
        ],
        "lcom": 0,
        "length": 1,
        "vocabulary": 1,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 2,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 1,
        "number_operators_unique": 0,
        "number_operands_unique": 1,
        "cloc": 0,
        "loc": 5,
        "lloc": 5,
        "mi": 171,
        "mIwoC": 171,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "ndesaleux\\valueObject\\Email\\InvalidEmail",
        "interface": false,
        "methods": [
            {
                "name": "fromValue",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Exception",
            "Throwable",
            "self"
        ],
        "lcom": 1,
        "length": 9,
        "vocabulary": 6,
        "volume": 23.26,
        "difficulty": 0.8,
        "effort": 18.61,
        "level": 1.25,
        "bugs": 0.01,
        "time": 1,
        "intelligentContent": 29.08,
        "number_operators": 1,
        "number_operands": 8,
        "number_operators_unique": 1,
        "number_operands_unique": 5,
        "cloc": 0,
        "loc": 9,
        "lloc": 9,
        "mi": 69.48,
        "mIwoC": 69.48,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 4,
        "relativeSystemComplexity": 4,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 4,
        "totalSystemComplexity": 4,
        "pageRank": 0.07,
        "afferentCoupling": 1,
        "efferentCoupling": 3,
        "instability": 0.75,
        "violations": {}
    },
    {
        "name": "ndesaleux\\valueObject\\Email\\Email",
        "interface": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getValue",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getDomain",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getCanonical",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 4,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 3,
        "nbMethodsSetters": 0,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "ndesaleux\\valueObject\\Email\\InvalidEmail"
        ],
        "lcom": 1,
        "length": 23,
        "vocabulary": 8,
        "volume": 69,
        "difficulty": 4.8,
        "effort": 331.2,
        "level": 0.21,
        "bugs": 0.02,
        "time": 18,
        "intelligentContent": 14.38,
        "number_operators": 7,
        "number_operands": 16,
        "number_operators_unique": 3,
        "number_operands_unique": 5,
        "cloc": 0,
        "loc": 28,
        "lloc": 28,
        "mi": 55.29,
        "mIwoC": 55.29,
        "commentWeight": 0,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 1.63,
        "relativeSystemComplexity": 2.63,
        "totalStructuralComplexity": 4,
        "totalDataComplexity": 6.5,
        "totalSystemComplexity": 10.5,
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "ndesaleux\\valueObject\\Luhn\\InvalidLuhn",
        "interface": false,
        "methods": [
            {
                "name": "fromValueWithInvalidChecksum",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "fromNoNumerical",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Exception",
            "self",
            "self"
        ],
        "lcom": 2,
        "length": 10,
        "vocabulary": 5,
        "volume": 23.22,
        "difficulty": 1,
        "effort": 23.22,
        "level": 1,
        "bugs": 0.01,
        "time": 1,
        "intelligentContent": 23.22,
        "number_operators": 2,
        "number_operands": 8,
        "number_operators_unique": 1,
        "number_operands_unique": 4,
        "cloc": 11,
        "loc": 25,
        "lloc": 14,
        "mi": 108.1,
        "mIwoC": 65.3,
        "commentWeight": 42.8,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 3.5,
        "relativeSystemComplexity": 3.5,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 7,
        "totalSystemComplexity": 7,
        "pageRank": 0.1,
        "afferentCoupling": 2,
        "efferentCoupling": 3,
        "instability": 0.6,
        "violations": {}
    },
    {
        "name": "ndesaleux\\valueObject\\Luhn\\Luhn",
        "interface": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "isValid",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getValue",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 1,
        "nbMethodsSetters": 0,
        "ccn": 7,
        "ccnMethodMax": 6,
        "externals": [
            "ndesaleux\\valueObject\\Luhn\\InvalidLuhn",
            "ndesaleux\\valueObject\\Luhn\\InvalidLuhn"
        ],
        "lcom": 1,
        "length": 69,
        "vocabulary": 26,
        "volume": 324.33,
        "difficulty": 18.86,
        "effort": 6115.94,
        "level": 0.05,
        "bugs": 0.11,
        "time": 340,
        "intelligentContent": 17.2,
        "number_operators": 25,
        "number_operands": 44,
        "number_operators_unique": 12,
        "number_operands_unique": 14,
        "cloc": 19,
        "loc": 57,
        "lloc": 38,
        "mi": 86.01,
        "mIwoC": 47.02,
        "commentWeight": 38.99,
        "kanDefect": 0.5,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 0.89,
        "relativeSystemComplexity": 4.89,
        "totalStructuralComplexity": 12,
        "totalDataComplexity": 2.67,
        "totalSystemComplexity": 14.67,
        "pageRank": 0.04,
        "afferentCoupling": 1,
        "efferentCoupling": 2,
        "instability": 0.67,
        "violations": {}
    },
    {
        "name": "ndesaleux\\valueObject\\CreditCard\\InvalidCreditCard",
        "interface": false,
        "methods": [
            {
                "name": "fromInvalidNumber",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "fromNotMatchingLuhnAlgorithm",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Exception",
            "self",
            "self"
        ],
        "lcom": 2,
        "length": 8,
        "vocabulary": 4,
        "volume": 16,
        "difficulty": 1,
        "effort": 16,
        "level": 1,
        "bugs": 0.01,
        "time": 1,
        "intelligentContent": 16,
        "number_operators": 2,
        "number_operands": 6,
        "number_operators_unique": 1,
        "number_operands_unique": 3,
        "cloc": 0,
        "loc": 14,
        "lloc": 14,
        "mi": 66.43,
        "mIwoC": 66.43,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 3,
        "relativeSystemComplexity": 3,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 6,
        "totalSystemComplexity": 6,
        "pageRank": 0.05,
        "afferentCoupling": 2,
        "efferentCoupling": 3,
        "instability": 0.6,
        "violations": {}
    },
    {
        "name": "ndesaleux\\valueObject\\CreditCard\\CreditCard",
        "interface": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getValue",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 1,
        "nbMethodsSetters": 0,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "ndesaleux\\valueObject\\CreditCard\\InvalidCreditCard",
            "ndesaleux\\valueObject\\Luhn\\Luhn",
            "ndesaleux\\valueObject\\CreditCard\\InvalidCreditCard"
        ],
        "lcom": 1,
        "length": 17,
        "vocabulary": 10,
        "volume": 56.47,
        "difficulty": 5.5,
        "effort": 310.6,
        "level": 0.18,
        "bugs": 0.02,
        "time": 17,
        "intelligentContent": 10.27,
        "number_operators": 6,
        "number_operands": 11,
        "number_operators_unique": 5,
        "number_operands_unique": 5,
        "cloc": 0,
        "loc": 21,
        "lloc": 21,
        "mi": 58.62,
        "mIwoC": 58.62,
        "commentWeight": 0,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 0.5,
        "relativeSystemComplexity": 4.5,
        "totalStructuralComplexity": 8,
        "totalDataComplexity": 1,
        "totalSystemComplexity": 9,
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 3,
        "instability": 1,
        "violations": {}
    }
]